server:
  port: 8081

spring:
  application:
    name: movie-catalog-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761

management:
  health:
    circuitbreakers:
      enabled : true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      movie-catalog-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED